name       : drawing
version    : 0.6.2
release    : 15
source     :
    - https://github.com/maoschanz/drawing/archive/0.6.2.tar.gz : 4a70690539fb402eaa0ece6501eb9f3e9aea7ae61ff54e16e88c3f2dd0e0e008
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : A simple drawing application for Linux.
description: |
    This application is a basic image editor, similar to Microsoft Paint, but aiming at the GNOME desktop.
builddeps  :
    - python3-cairo
    - python-gobject
rundeps    :
    - libgtk-3
    - python3-cairo
    - python-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
