name       : drawing
version    : 0.4.11
release    : 8
source     :
    - https://github.com/maoschanz/drawing/archive/0.4.11.tar.gz : a573a3f1720f67411841262b92a668218578c6072e3564603a11e230f6f313ff
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : A simple drawing application for Linux.
description: |
    This application is a basic image editor, similar to Microsoft Paint, but aiming at the GNOME desktop.
rundeps    :
    - libgtk-3
    - python3-cairo
    - python3-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
