name       : drawing
version    : 0.4.12
release    : 9
source     :
    - https://github.com/maoschanz/drawing/archive/0.4.12.tar.gz : 3a41d0a3a1f4b7064cd38b715437ec72f7d21c2f36ec7c2a36cca4fcf91ef93b
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : A simple drawing application for Linux.
description: |
    This application is a basic image editor, similar to Microsoft Paint, but aiming at the GNOME desktop.
rundeps    :
    - libgtk-3
    - python3-cairo
    - python3-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
