name       : drawing
version    : 0.8.5
release    : 25
source     :
    - https://github.com/maoschanz/drawing/archive/refs/tags/0.8.5.tar.gz : d9c3ab7005097f22e4940045ff047419e765a3ed3e5e8fa0da50418b82f98fbc
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : A simple drawing application for Linux.
description: |
    This application is a basic image editor, similar to Microsoft Paint, but aiming at the GNOME desktop.
builddeps  :
    - python3-cairo
    - python-gobject
rundeps    :
    - libgtk-3
    - python3-cairo
    - python-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
