name       : drawing
version    : 0.4.9
release    : 5
source     :
    - https://github.com/maoschanz/drawing/archive/0.4.9.tar.gz : 6e22039bb51719bace16f5c304ccf2d6239410e373717f81cd052ff62d6728a3
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : A simple drawing application for Linux.
description: |
    This application is a basic image editor, similar to Microsoft Paint, but aiming at the GNOME desktop.
rundeps    :
    - libgtk-3
    - python3-cairo
    - python3-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
