name       : drawing
version    : 0.6.4
release    : 17
source     :
    - https://github.com/maoschanz/drawing/archive/0.6.4.tar.gz : ff92f0d1b681c9f2e79f3dbd777503e2c67de289405ea67d9cbe1a120544172c
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : A simple drawing application for Linux.
description: |
    This application is a basic image editor, similar to Microsoft Paint, but aiming at the GNOME desktop.
builddeps  :
    - python3-cairo
    - python-gobject
rundeps    :
    - libgtk-3
    - python3-cairo
    - python-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
