name       : drawing
version    : 0.6.5
release    : 18
source     :
    - https://github.com/maoschanz/drawing/archive/0.6.5.tar.gz : dd9ce1ef32e95f2e27fb9fad45727780218a198863ac14ab1f5018ad613cc7ff
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : A simple drawing application for Linux.
description: |
    This application is a basic image editor, similar to Microsoft Paint, but aiming at the GNOME desktop.
builddeps  :
    - python3-cairo
    - python-gobject
rundeps    :
    - libgtk-3
    - python3-cairo
    - python-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
