name       : drawing
version    : 0.8.2
release    : 21
source     :
    - https://github.com/maoschanz/drawing/archive/0.8.2.tar.gz : f3bc4630e66bdd1ca45c19575f97e78f8e54a3fb4aaaf83dba03e26c9868ac01
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : A simple drawing application for Linux.
description: |
    This application is a basic image editor, similar to Microsoft Paint, but aiming at the GNOME desktop.
builddeps  :
    - python3-cairo
    - python-gobject
rundeps    :
    - libgtk-3
    - python3-cairo
    - python-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
